theopenlane/core

go.mod
go.sum
internal/ent/schema/apitoken.go
internal/ent/schema/personalaccesstoken.go

updating references, need to remove other references to keygen before the package is removed here

update keygen references

---

internal/ent/hooks/user.go
internal/httpserve/handlers/oauth_login_handlers_test.go

feat: add default user avatar if one is not set

---

internal/httpserve/route/mta-sts.txt
internal/httpserve/route/router.go
internal/httpserve/route/static.go

This isn't something we need to worry about doing especially given most of the email logic has already been ported out into newman

remove mta sts sillyness

---

internal/httpserve/route/static.go

fixes broken apple merchant route

fix apple merchant route

---

.buildkite/pipeline.yaml

relevant github issue: https://github.com/aquasecurity/trivy/discussions/7668

bug: rate limiting trivy db, try using the mirror source

---

config/config.go

Adds some additional logging to the `Load` function for easier debugging on where the problem with a config might lie, and a check to fail if the file doesn't exist prior to attempting to load the file / unmarshall

add better error logging and file / directory check

---

db/migrate.go
db/seed/01_seed_root_org.sql
internal/entdb/client.go

but in its own directory so I don't blow it away again :-D

add back the seed data

---

.buildkite/pipeline.yaml

Depends on https://github.com/theopenlane/build-image/pull/15

feat: rover publish graph schema on tagged releases

---

renovate.json

groups renovate patch updates into a single PR: https://docs.renovatebot.com/presets-group/

group renovate patch updates

---

go.mod

go version

---

internal/httpserve/handlers/acccountaccess.go
internal/httpserve/handlers/acccountroles.go
internal/httpserve/handlers/acccountrolesorganization.go
internal/httpserve/handlers/forgotpassword.go
internal/httpserve/handlers/invite.go
internal/httpserve/handlers/login.go
internal/httpserve/handlers/openapi.go
internal/httpserve/handlers/refresh.go
internal/httpserve/handlers/register.go
internal/httpserve/handlers/resendemail.go
internal/httpserve/handlers/resetpassword.go
internal/httpserve/handlers/switch.go
internal/httpserve/handlers/tfavalidate.go
internal/httpserve/handlers/verifyemail.go
internal/httpserve/handlers/verifysubscribe.go
internal/httpserve/handlers/webauthn.go
internal/httpserve/server/openapi.go
pkg/models/models.go

- removes unused models
- adds bind function for webauthn
- adds functions for security requirements
- updates tags

fix up openapi spec, add security requirements, add webauthn

---

internal/graphapi/generated/schema.graphql

not sure why these were auto-removed

fix: remove invalid stripeID from org settings schema

---

.github/workflows/releaser.yml

Revert "bug: switch back to 20250106.725 version of runner"

---

config/config-dev.example.yaml
go.mod
go.sum
internal/httpserve/handlers/tools_test.go
internal/httpserve/serveropts/option.go
pkg/middleware/cors/cors.go

- adds cors mw to tests; see the same 401 error I had without "*" in my allowed origins
- upgrades echox
- no longer swallows error on bad cors config

add cors to mw for tests, add * to config, echox update

---

pkg/objects/README.md

Updates README to provide attribution to @adelowo 's gulter project

provide attribution

---

internal/graphapi/clientschema/schema.graphql
internal/graphapi/control_test.go
internal/graphapi/controlextended.resolvers.go
internal/graphapi/generated/controlextended.generated.go
internal/graphapi/generated/root_.generated.go
internal/graphapi/model/gen_models.go
internal/graphapi/query/controlextended.graphql
internal/graphapi/schema/controlextended.graphql
pkg/openlaneclient/graphclient.go
pkg/openlaneclient/models.go

- adds ability to set the programID on clone of controls

feat: add program id to control on clone

---

.buildkite/pipeline.yaml

This uses triggers to start the `core-deploy` pipeline passing along the image tag
https://github.com/theopenlane/core-deploy/blob/main/.buildkite/pipeline.yaml

update pipeline to trigger core-deploy builds 

---

.buildkite/pipeline.yaml

This fixes and updates the trigger syntax.

Fix trigger syntax

---

.buildkite/pipeline.yaml

tiny fix per env :)) 
Failed because of this  at https://buildkite.com/theopenlane/core/builds/2895/steps?sid=01961b91-4a43-4b0d-84a7-9b81bcc03e04

use CORE_TAG instead for the pipeline trigger 

---

.buildkite/pipeline.yaml

Trigger step should depend on tagging docker image not the build step

---

internal/graphapi/orgmembership.resolvers.go
internal/graphapi/subscriber.resolvers.go

these accidentally got reverted on a subsequent PR

feat: add back subscriber +org member resolver bulk owner

---

fga/model/model.fga
internal/graphapi/auditlog_test.go
internal/graphapi/query/auditlog.graphql
pkg/openlaneclient/graphclient.go

Fixes error and adds simple sanity test to ensure we aren't getting errors
```
{
"errors": [
{
"message": "POST validation error for ListObjects POST with body {\"code\":\"type_not_found\",\"message\":\"type 'action_plan' not found\"}\n with error code type_not_found error message: type 'action_plan' not found",
"path": [
"auditLogs"
]
}
],
"data": null,
"extensions": {
"auth": {
"authentication_type": "api_token",
"authorized_organization": [
"01JRVR78SGZQZGNHXAP002MJJ6"
]
},
"server_latency": "14.901786ms",
"trace_id": "vAroSfKPUalVOvnuqxxiodtzXSykiVVm"
}
}
```

bug: fix missing fga types, add audit log sanity test

---

config/config-dev.example.yaml

cleaning up example config for OSS contributors

fix: fix quote, cleanup example config

---

internal/ent/hooks/usersettings.go
internal/graphapi/usersetting_test.go

fixes bug + adds tests to confirm

bug: fix updating default org for non-owners of org

---

internal/ent/hooks/event.go
internal/ent/interceptors/orgsubscription.go
internal/httpserve/handlers/webhook.go
internal/httpserve/handlers/webhook_test.go
pkg/entitlements/client.go
pkg/entitlements/customers.go
pkg/entitlements/errors.go
pkg/entitlements/helpers.go
pkg/entitlements/helpers_test.go
pkg/entitlements/portalsession.go
pkg/entitlements/prices.go
pkg/entitlements/products.go
pkg/entitlements/stripe_test.go
pkg/entitlements/subscriptions.go
pkg/entitlements/test/main.go
pkg/entitlements/tuples.go

- moves to new stripe client
- fixes a bug where expires at was the zero date because we were using EndDate instead of TrialEnd

fixes for new stripe client

---

internal/ent/interceptors/auditlogs.go
internal/ent/interceptors/filter.go
internal/ent/schema/mixin_objectowned.go
internal/graphapi/control_test.go
internal/graphapi/internalpolicy_test.go
internal/graphapi/models_test.go
internal/graphapi/program_test.go
internal/graphapi/query/internalpolicy.graphql
pkg/openlaneclient/graphclient.go

fixes a bug where you could associate objects to system-owned controls

fix: do not allow controls from system to be linked, require edit

---

cmd/cli/cmd/dnsverification/update.go
db/migrations-goose-postgres/20250526222006_dns_ssl_verification_statuses.sql
db/migrations-goose-postgres/atlas.sum
db/migrations/20250526222003_dns_ssl_verification_statuses.sql
db/migrations/atlas.sum
internal/ent/generated/dnsverification.go
internal/ent/generated/dnsverification/dnsverification.go
internal/ent/generated/dnsverification/where.go
internal/ent/generated/dnsverification_create.go
internal/ent/generated/dnsverification_update.go
internal/ent/generated/dnsverificationhistory.go
internal/ent/generated/dnsverificationhistory/dnsverificationhistory.go
internal/ent/generated/dnsverificationhistory/where.go
internal/ent/generated/dnsverificationhistory_create.go
internal/ent/generated/dnsverificationhistory_update.go
internal/ent/generated/gql_mutation_input.go
internal/ent/generated/gql_where_input.go
internal/ent/generated/migrate/schema.go
internal/ent/schema/dnsverification.go
internal/graphapi/clientschema/schema.graphql
internal/graphapi/dnsverification_test.go
internal/graphapi/generated/root_.generated.go
internal/graphapi/models_test.go
internal/graphapi/schema/ent.graphql
pkg/enums/custom_domain_status.go
pkg/enums/custom_domain_status_test.go
pkg/openlaneclient/graphclient.go
pkg/openlaneclient/models.go

Duplicate the statuses that cloudflare's API spits out.

Conform verification statuses with cloudflare statuses

---

db/migrations-goose-postgres/20250617071502_owner_id_index.sql
db/migrations-goose-postgres/atlas.sum
db/migrations/20250617071458_owner_id_index.sql
db/migrations/atlas.sum
internal/ent/generated/migrate/schema.go
internal/ent/schema/customdomain.go
internal/ent/schema/mixin_objectowned.go
internal/graphapi/clientschema/schema.graphql
internal/graphapi/control_test.go
internal/graphapi/controlextended.resolvers.go
internal/graphapi/generated/root_.generated.go
internal/graphapi/models_test.go
internal/graphapi/query/controlextended.graphql
internal/graphapi/schema/controlextended.graphql
pkg/corejobs/internal/olclient/mocks/mocks.go
pkg/openlaneclient/graphclient.go

- returns a distinct list of existing [sub]control [sub]categories
- adds a index on `owner_id` where `deleted_at is null` to all tables
```
{
"data": {
"controlCategories": [
"Access Control",
"Assessment, Authorization, and Monitoring",
"Audit and Accountability",
"Availability",
"Awareness and Training",
"Confidentiality",
"Configuration Management",
"Context of the organization",
"Contingency Planning",
"Detect",
"Govern",
"Identification and Authentication",
"Identify",
"Improvement",
"Incident Response",
"Information security policies",
"Leadership",
"Maintenance",
"Media Protection",
"Operation",
"People controls",
"Performance evaluation",
"Personally Identifiable Information Processing and Transparency",
"Personnel Security",
"Physical and Environmental Protection",
"Physical …
```

feat: add category and subcategory resolvers

---

internal/ent/generated/gql_mutation_input.go
internal/ent/schema/organization.go
internal/ent/schema/user.go
internal/graphapi/clientschema/schema.graphql
internal/graphapi/generated/root_.generated.go
internal/graphapi/schema/ent.graphql
pkg/openlaneclient/models.go

these schemas all skip the entgql generation on the schema, but were not skipped on the back-ref edges.

cleanup edges that should be skipped

---

go.mod
go.sum

Needed to cut a release and not so sure when rennovate bot would do that

Bump gqlgen-plugins

---

internal/graphapi/query/organization.graphql
pkg/openlaneclient/graphclient.go

we should consider having a simpler + focused CLI we distribute vs. the queries that are used within tests in the near future

bug: reduce complexity of org query

---

cmd/cli/cmd/root.go
config/config.go
go.mod
go.sum

Revert "fix(deps): update module github.com/knadh/koanf/providers/env to v2"

---

internal/ent/generate/templates/entgql/pagination.tmpl
internal/ent/generated/gql_pagination.go
internal/ent/schema/mixin_objectowned.go
internal/ent/schema/task.go

reverting for now to make sure main is releasable

revert list objects for now

---

.buildkite/cleanup-draft-prs.sh
.buildkite/draft-pr-automation.sh
.buildkite/helm-automation.sh
.buildkite/lib/common.sh
.buildkite/lib/helm.sh
.buildkite/post-merge-pr-automation.sh
.buildkite/slack-utils.sh
.buildkite/templates/helm-update-notification.json
.buildkite/tests/Taskfile.yaml
.buildkite/tests/cleanup-draft-prs.bats
.buildkite/tests/draft-pr-automation.bats
.buildkite/tests/helm-automation.bats
.buildkite/tests/link-pr-automation.bats
.buildkite/tests/slack-utils.bats
Taskfile.yaml

- fixes certain scenarios which would lead to an exit 1 circumstance when there are no changes
- changed the behavior to only open draft PR / comment on core PR's if the PR itself contains changes to the config, rather than commenting / opening drafts any time the configuration doesn't match generally
- removed some echo / print lines that were getting appended to the summaries
- adds a bunch of BATS tests to help confirm behavior / output of the scripts
- changed draft PR closing logic to close the openlane-infra draft PR's in any situation a core repo PR didn't exist

Additional CI / buildkite enhancements for smoother Helm integration

---

.buildkite/post-merge-pr-automation.sh

fix - use the right CI script libs

---

.buildkite/post-merge-pr-automation.sh

This is failing whenever there are Draft PRs open, so its specific to the sed here. Trying to see if this will fix it

attempt to fix bash on draft pr rename

---

pkg/corejobs/test/delete_export_job/main.go
pkg/corejobs/test/export/main.go

Add cli to test job export features

---

.goreleaser.yaml

if we are having renovate do this; we don't actually need this here I think

remove brew, we are using renovate

---

.github/workflows/releaser.yml
.goreleaser.yaml

- renovate is a pain for multi-distro updates; going to see if adding this back works better
- also adds a mod cache

add homebrew_casks back to goreleaser

---

internal/graphapi/export_test.go
pkg/corejobs/export.go

bug: fix whereInput for two work schemas, get 100 at a time, not 2

---

internal/httpserve/handlers/ent.go
internal/httpserve/handlers/oauth_login.go
internal/httpserve/handlers/oauth_register.go
internal/httpserve/handlers/sso.go
internal/httpserve/handlers/webauthn.go
pkg/metrics/helpers.go

only some login path's recorded the metrics, adding to all paths as well as registration metrics.

feat: add missing login + registration metrics

---

internal/ent/hooks/orgmodule.go
internal/httpserve/handlers/webhook.go
internal/httpserve/handlers/webhook_helpers.go

- remove all modules except the base when a subscription is deleted 
- when a module is removed from stripe, remove the module in the db and fga 
- handle bulk update ( soft deletion ) fga uodstes

Feature tuple updates based off stripe events

---

internal/ent/hooks/documentdata.go
internal/graphapi/trustcenternda_test.go

Add the nda_signed relation to the user <-> trust center relationship when an anonymous user signs the nda.

add nda_signed relation when an NDA gets signed

---

cmd/cli/cmd/root.go
config/config.go
go.mod
go.sum

fix(deps): update module github.com/knadh/koanf/providers/env to v2

---

internal/httpserve/handlers/webhook.go

fix: actually update the subscription id if we find it via metadata
