.buildkite/pipeline.yaml, docker/all-in-one/Dockerfile.all-in-one, docker/all-in-one/docker_entrypoint.sh
- updates the GCR repo and region
- fixes the docker image to have dbx references
- tested and was able to confirm a published image in GCR
=> get the aio image building

docker/all-in-one/Dockerfile.all-in-one
Segfault specific to connection to sslmode=require psql connection. _Something_ that is upgraded since the last time this was attempted changed causing this segfault. I confirmed this is not related to go1.23.0 and a few other libraries, but added the `-tags osusergo` to the go build fixes this and this tag will force all os/user calls to use the native Go implementations instead of c implementations. 
Prior stacktrace: 
```
SIGSEGV: segmentation violation
PC=0x0 m=0 sigcode=1 addr=0x0
signal arrived during cgo execution
goroutine 1 gp=0x40000021c0 m=0 mp=0x7918ba0 [syscall]:
runtime.cgocall(0x3a19794, 0x400127d7e8)
/usr/local/go/src/runtime/cgocall.go:157 +0x44 fp=0x400127d7b0 sp=0x400127d770 pc=0x407284
os/user._Cfunc_mygetpwuid_r(0xfffc, 0x4000125c00, 0x400, 0x4000d01d1c, 0x4000d01d30) …
```
=> fix aio image from running with sslmode psql

.goreleaser.yaml, cmd/cli/cmd/client.go, cmd/cli/cmd/root.go, cmd/root.go
Listing the CLI on brew as "core" would likely be confusing so adjusted the service name in `/cmd` being used as well as some minor tweaks to the goreleaser config to publish the artifacts as "openlane" vs. "core"
=> update goreleaser and cli name

.pre-commit-config.yaml, pkg/middleware/ratelimiter/README.md, pkg/middleware/ratelimiter/doc.go, pkg/middleware/ratelimiter/examples/http_middleware.go/http_middleware.go, pkg/middleware/ratelimiter/examples/simple/simple.go, pkg/middleware/ratelimiter/map_limit_store.go, pkg/middleware/ratelimiter/map_limit_store_test.go, pkg/middleware/ratelimiter/ratelimiter.go, pkg/middleware/ratelimiter/ratelimiter_test.go, sonar-project.properties
Adds a new generic rate limiter based on cloudflare's design
=> Feat ratelimiter

.buildkite/pipeline.yaml, README.md, Taskfile.yaml, db/README.md, db/Taskfile.yaml, db/create_migrations.go, db/migrate.go, docs/tools.md, internal/entdb/client.go, internal/graphapi/errors.go
- Removes support for sqlite and libsql, with the addition of `riverqueue` which requires `postgres` it does not seem worth it to support sqlite variants. However, making this it's own PR outside of the river integration so if we ever want to add it back we have a simple reference point to do so.
=> remove libsql and sqlite support

.buildkite/pipeline.yaml
I'd like to start testing postgres 17, but at least locally our tests take 3x as long due to CPU throttling so keeping 16 as the default for now.
=> feat: test support for pg 17, remove pg 15

.buildkite/pipeline.yaml
- The default version in the plugin is 6+ months old (v0.49.1), current version is `v0.55.2`
- Updates deprecated config options
=> deps: upgrade trivy version to 0.55.2

.github/labeler.yml
the current labeler is removing the dependencies label because the conditions are not met
=> add dependabot + renovate to deps labeler

.buildkite/pipeline.yaml, .golangci.yaml, Taskfile.yaml, pkg/middleware/ratelimiter/ratelimiter.go
This now locally takes:
```
INFO Execution took 2m42.106713042s  
```
vs. before the changes:
```
INFO Execution took 4m54.794890834s
```
CI is passing in about 7-8 minutes. 
Changes: 
- `test: false` will now include all tests files from the linter.
- No linters were removed, I just re-orded so I could see the default vs. what additional ones we have added are. Removing some didn't really speed up the process. 
- removed `fast` and `fix` from the ci run. The first run of `fast` is always slower, its not recommended to run in ci. And `fix` should never be run in CI because the changes need to be pushed to the branch.
=> golangci updates for speed

docker/docker-compose-riverboat.yml, pkg/objects/objects.go, pkg/objects/options.go, query/feature.graphql, query/internalpolicyhistory.graphql, query/organizationhistory.graphql, query/standard.graphql, query/usersettinghistory.graphql
these fixes came from running the command `pre-commit run --show-diff-on-failure --color=always --all-files`. 
Note: I had to run the command multiple times to get to a final passing state. Seems like the typos ran first, stages changes then killed the pre-commit, running it again fixes the graphql formatting.
=> fixes from pre-commit run: typos and graphql formatting

README.md
`task run-dev` failed with
```
Error: open fga/model/openlane.fga: no such file or directory
exit status 1
task: Failed to run task "run-dev": exit status 1
```
I fixed this by running `cp config/config-dev.example.yaml .config/.config.yaml`.
=> Document adding openlane.fga

.buildkite/pipeline.yaml
I thought I had put these on large, but I guess I was defaulting to medium. Let's see if this helps the failures/timeouts
=> use hosted large for core tests

.github/ISSUE_TEMPLATE/bugreport.yml
As I was creating some new issues on this repository I randomly noticed a link on the page that took me to some new features github has made available which allows you to control user inputs / forms inside of the github UI. 
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
I followed the example almost directly ^ but you have to commit the file to the repo to actually see the flow in action
=> add new issue form thingy

.buildkite/pipeline.yaml, tools.go
Only run generate + tests when PRs are from renovate
=> limit the builds from renovate; remove unused fgax/mockery

.buildkite/pipeline.yaml, internal/graphapi/internalpolicy.resolvers.go
This will allow us to use the UI steps to change queues if we need instead of having to PR for the default. Once we have more capacity I'll remove the `hosted-large` overrides as well:
Steps in UI are now: 
```
agents:
size: "large"
queue: "self-hosted-garage-vms"
steps:
- label: ":pipeline:"
command: "buildkite-agent pipeline upload"
agents:
queue: "self-hosted-garage-vms"
size: "small"
```
=> remove default queue from top, this will be set in the UI instead

.github/labeler.yml, internal/graphapi/organization_test.go, internal/graphapi/testdata/uploads/orgs.csv, internal/middleware/objects/middleware.go
- fixes csv upload, the files were being saved to the `files` schema and then unable to be read for input. These files should instead be skipped by the middleware
- fixes labeler that apparently did not save on my last PR
Confirmed `opencloud-cloud` works correctly again to seed data:
```
task cli:init                                          
task: [cli:init] go run cmd/cli/main.go seed init
> registering users...  10% [>              ]  [0s:0s]{"level":"info","app":"openlane-cloud","file":{},"time":"2024-12-14T20:29:02-07:00","message":"loaded CSV file"}
> creating organizations...  20% [==>            ]  [1s:4s]{"level":"info","app":"openlane-cloud","file":"demodata/orgs.csv","time":"2024-12-14T20:29:03-07:00","message":"loading organizations"} …
```
=> fix: csv upload should not save file

.buildkite/pipeline.yaml
This will allow us to easily switch to a hosted queue if needed for some reason by setting the env vars in the UI vs. having to a PR a change to the pipeline itself.
If you override the env vars to a hosted queue, the tags should be ignored.
=> Use env vars to set large/small jobs

internal/httpserve/handlers/acccountrolesorganization.go, internal/httpserve/handlers/openapi.go, internal/httpserve/handlers/verifyemail.go, internal/httpserve/handlers/verifysubscribe.go, internal/httpserve/route/accountrolesorganization.go, internal/httpserve/server/openapi.go
- Fixes a duplicate `AccountRolesOrganization`, by changing one to `AccountRolesOrganizationByID`
- Fixes the `ErrorReponse` ref missing, which was changed to `ErrorReply`
- Fixes the `Get` calls with path params + query params instead of request body
- removes invalid username/pwd auth + api token auth; all auth is via `Bearer`
=> fixup a few errors in our OpenAPI spec for REST endpoints

.pre-commit-config.yaml, internal/httpserve/handlers/ent.go, internal/httpserve/handlers/errors.go, internal/httpserve/handlers/webhook.go, internal/httpserve/route/router.go, internal/httpserve/route/webhook.go, internal/httpserve/serveropts/option.go, pkg/entitlements/README.md, pkg/entitlements/client.go, pkg/entitlements/customers.go, pkg/entitlements/events.go, pkg/entitlements/models.go, pkg/entitlements/subscriptions.go
- initial implementation of a route + handler which receives stripe webhooks, performs signature verification, and matches event by type to perform event unmarshaling
- current implementation creates internal event ID references and performs look ups to prevent double processing
- no actual update logic is being performed by the handler - future pull requests will add additional logic as necessary but this will allow is to begin receiving and logging webhooks
- other misc changes: pre-commit update, removal of unnecessary white space / line breaks, initialize stripe client with webhook secret in serverOpts
=> Feat stripe webhook receiver

.buildkite/pipeline.yaml
Adds a graphql linter for schema changes, set to soft fail.
Example on error: https://buildkite.com/theopenlane/core/builds/1931
Example on success: https://buildkite.com/theopenlane/core/builds/1932
Moves atlas schema publish to the publish step
=> feat: apollo linter

pkg/entitlements/subscriptions.go
Calling `iter.Next() ` early caused the iter to advance by 1 without getting the result; we should instead check the error after it is called.
=> bug: fix missing feature in subscriptions

Taskfile.yaml, internal/ent/generated/runtime/runtime.go, internal/ent/generated/tfasetting/tfasetting.go, internal/ent/hooks/tfasettings.go, internal/ent/schema/tfasetting.go, internal/graphapi/clientschema/schema.graphql, internal/graphapi/generated/actionplan.generated.go, internal/graphapi/generated/root_.generated.go, internal/graphapi/generated/tfasetting.generated.go, internal/graphapi/model/gen_models.go, internal/graphapi/models_test.go, internal/graphapi/query/tfasetting.graphql, internal/graphapi/schema/tfaextended.graphql, internal/graphapi/tfahelpers.go, internal/graphapi/tfasetting.resolvers.go, internal/graphapi/tfasetting_test.go, pkg/openlaneclient/graphclient.go, pkg/openlaneclient/models.go
- TFA secret + QRCode should be be generated when tfa settings are created and `totpAllowed` is set to true
- Recovery codes should only be returned when verifying or regenerating recovery codes
Flow: 
- Create TFA setting with `totpAllowed=true`, tfa secret generated, qr code returned (if requested)
- Update TFA setting with `verified`, recovery codes returned
- Update TFA setting with `regenBackupCodes`, new recovery codes returned
- If a TFA setting is created with `totpAllowed=false`, an update will also trigger the creation of the tfa secret
- If totpAllowed is set to false, the secret and recovery codes will be removed and the users 2fa enabled setting will be set to false
=> feat: qr code on create, recovery codes on verification of device

fga/model/model.fga, internal/ent/hooks/authzmutationhelpers.go, internal/ent/hooks/authzmutationhelpers_test.go, internal/ent/hooks/group.go, internal/ent/hooks/objectownedtuples.go, internal/ent/hooks/organization.go, internal/ent/hooks/orgownedtuples.go, internal/ent/hooks/program.go, internal/ent/hooks/task.go, internal/ent/schema/mixin_orgowned.go, internal/graphapi/control_test.go, internal/graphapi/controlobjective_test.go, internal/graphapi/narrative_test.go, internal/graphapi/risk_test.go, internal/graphapi/subcontrol_test.go
Objects that were being created with an API token we not accessible to any human user in the org. Organization owners should always have edit access to all objects created within the system. 
This adds an additional `orgnazation#owner` relation to the compliance objects that were being "orphaned" (not accessible outside the API token unless edges to a program/group were added) to be visible by the organization owner.
=> bug:org owner access to compliance objects 

.github/workflows/releaser.yml
The latest macos broke our cli build; where it will now try to save to the `keyring` (backup file) instead of the `keychain`. Hopeing this will fix it until I can figure out the things to get it working. 
```
Enter passphrase to unlock "/Users/sarahfunkhouser/Library/Application Support/openlane/keyring": 
```
The last working verison of the cli was `0.6.10`
=> bug: switch back to 20250106.725 version of runner

internal/httpserve/handlers/ent.go, internal/httpserve/handlers/tfavalidate.go
When a user is setting up a device, we use this endpoint to verify it is setup correctly before setting `verified=true`. This check prevents this from being possible.
=> bug: don't check if tfa is enabled on validate, this prevents validation on setup

internal/httpserve/serveropts/option.go
- ensure we set `s.Config.Handler.RedisClient` to be used by the totp manager
- remove duplicate `WithRedis` setting
=> bug: fix redis client nil

cmd/serve.go, internal/httpserve/handlers/handlers.go, internal/httpserve/handlers/register.go, internal/httpserve/handlers/verify_test.go, internal/httpserve/handlers/verifyemail.go, internal/httpserve/server/openapi.go, pkg/models/models.go
- We currently return the `verify` token on the `register` request to make dev easier, however, we shouldn't directly return the email verification token on the response in prod. This changes it to only return it when the  server is running with `dev:true` and removes the field from the OpenAPI spec. 
`server.dev=true`
```
(⎈ |default:default)➜  core-more git:(feat-verify) ✗ go run cmd/cli/main.go register --email="testy2@theopenlane.io" --first-name=sarah --last-name=funk -p test\!1234asd -z json
{
"email": "testy2@theopenlane.io",
"message": "Welcome to Openlane!",
"success": true,
"token": "eYPdf61gNyT6__OqT-_6eUwak7j9hkBKxI9z7gO4ZGM",
"user_id": "01JJHTJA7DY351YM6DJH5N6VN3"
}
```
`server.dev=false`
```
(⎈ |default:default)➜  core-more git:(feat-verify) ✗ go run cmd/cli/main.go …
```
=> feat: only return register token against localhost, add descriptions to fields

go.mod, go.sum, internal/graphapi/clientschema/schema.graphql, internal/graphapi/generated/actionplan.generated.go, internal/graphapi/generated/root_.generated.go, internal/graphapi/generated/tfasetting.generated.go, internal/graphapi/model/gen_models.go, internal/graphapi/query/tfasetting.graphql, internal/graphapi/schema/tfaextended.graphql, internal/graphapi/tfahelpers.go, internal/graphapi/tfasetting.resolvers.go, internal/graphapi/tfasetting_test.go, internal/httpserve/serveropts/option.go, pkg/openlaneclient/graphclient.go, pkg/openlaneclient/models.go
- updates iam for default config settings
- actually uses the config values for recovery code details
- adds `tfaSecret` (decrypted) to response in the same conditions as `qrCode`
example response on update:
```
{
"data": {
"updateTFASetting": {
"qrCode": "otpauth://totp/theopenlane.io:mitb@theopenlane.io?algorithm=SHA1&digits=6&issuer=theopenlane.io&period=30&secret=OCO6JNXT6QS65GPQ653ISMUDVVPHUYQ4",
"recoveryCodes": [
"3MIA7648",
"T7DGWPR5",
"W3GJC2Q9",
"S72UGSYR",
"RBCGLAT3",
"Y7W4PCRU",
"U3OBLCCK",
"PF0MMGI5",
"9ELXS2OG",
"WAJ7G5Z9",
"HE4L5GXT",
"SQ1MS2OC",
"WS0TTKLN",
"5CO4KHDC",
"MRPON148",
"6F0SHE0T"
],
"tfaSecret": "OCO6JNXT6QS65GPQ653ISMUDVVPHUYQ4",
"tfaSetting": {
"id": "01JJJNYD20HRQWH7JBTDSGHM6Z",
"verified": true,
"totpAllowed": true
}
}
},
"extensions": {
"auth": { …
```
=> feat: option to also return tfa secret on update/create in addition to qr code

internal/ent/hooks/usersettings.go
settings.isTFAEnabled should allow the 2fa to be disabled/enabled without completely removing the user's tfa setting. This will allow for a temporary disable of the setup without requiring the user to resetup their 2fa when they turn it back on.
=> allow tfa to be disabled without removing the settings

internal/ent/hooks/tfasettings.go, internal/graphapi/tfasetting_test.go
- fixes test to accurately check for this use case
- fixes the empty string to be nil when cleared so a new TFA secret gets generated
=> bug: fix renable totpAllowed = true after disable

internal/ent/interceptors/user.go, internal/graphapi/clientschema/schema.graphql, internal/graphapi/generated/actionplan.generated.go, internal/graphapi/generated/root_.generated.go, internal/graphapi/group_test.go, internal/graphapi/groupextended.resolvers.go, internal/graphapi/grouppermissionshelpers.go, internal/graphapi/models_test.go, internal/graphapi/query/group.graphql, internal/graphapi/schema/groupextended.graphql, pkg/openlaneclient/graphclient.go, pkg/openlaneclient/models.go
- Allows a group to be created by cloning permissions and members from another group
- Allows a group to be updated by cloning permission from another group, these will be added in addition to existing permissions the group already has
- **updates do no allow cloning members
- tests added to ensure permissions + members get added 
- TODOs in here because we should automate this with codegen, but will follow-up later on that. 
```
mutation CreateGroupByClone($groupInput: CreateGroupInput!, $inheritGroupPermissions: ID, $cloneGroupMembers: ID) {
createGroupByClone(groupInput: $groupInput, inheritGroupPermissions: $inheritGroupPermissions, cloneGroupMembers: $cloneGroupMembers) {
group {
id
displayID
members {
id
user {
firstName
lastName
}
}
permissions {
id
displayID
name
objectType …
```
=> feat: clone permissions and members for group creation

internal/graphapi/errors.go, internal/graphapi/onboarding.resolvers.go, internal/graphapi/onboarding_test.go, internal/graphapi/organization.resolvers.go, internal/graphapi/organization_test.go
restricts the org + onboarding create resolvers to require JWT authentication
=> feat: restrict org creation to JWT authentication

internal/ent/generated/control/control.go, internal/ent/generated/controlobjective/controlobjective.go, internal/ent/generated/documentdata/documentdata.go, internal/ent/generated/evidence/evidence.go, internal/ent/generated/narrative/narrative.go, internal/ent/generated/note/note.go, internal/ent/generated/risk/risk.go, internal/ent/generated/runtime/runtime.go, internal/ent/generated/subcontrol/subcontrol.go, internal/ent/generated/task/task.go, internal/ent/schema/entity.go, internal/ent/schema/entitytype.go, internal/ent/schema/invite.go, internal/ent/schema/mixin_objectowned.go, internal/ent/schema/mixin_orgowned.go, internal/ent/schema/mixin_userowned.go, internal/ent/schema/subscriber.go, internal/ent/schema/template.go, internal/graphapi/control_test.go, internal/graphapi/controlobjective_test.go, internal/graphapi/evidence_test.go, internal/graphapi/narrative_test.go, internal/graphapi/procedure_test.go, internal/graphapi/task_test.go
Fixes a bug that would return all tasks for a user; instead of being filtered on the current organization ID. This was noticed on tasks, but was an issue for all object owned schemas. Adds tests to confirm behavior.
=> bug: object owned objects with org owners should filter on organzation

internal/ent/generated/runtime/runtime.go, internal/ent/hooks/user.go, internal/ent/schema/user.go, internal/httpserve/handlers/register_test.go
Validator was preventing setting my display name to "Sarah Funkhouser" - this shouldn't be a slug - but the user's full name ideally.
=> feat: remove validator on display name, default to first and last name if available

internal/ent/base/entinit.tmpl
fixes the base schema 
- removes invalid var; updated to `SchemaFuncs`
- fixes imports to be valid based on functions that are commented out/not used any more
Test with a brand new schema and runs cleanly the first run now
=> bug: fix base schema template

internal/graphapi/invite.resolvers.go, internal/graphapi/invite_test.go
We overload the create invite endpoint to do an update if the invitation already exists for the email, this works fine except on the bulk endpoints. Because of how the bulk endpoints work; even though the invites were properly updated; the full mutation wasn't executed so the node didn't have the results returned. 
I tried a few other options
- like attempting to create (instead of get first); but the error results in the transaction being aborted 
- pulling the invites in the resolver if they were nil; this didn't return the correct send attempts; assuming because the transaction wasn't yet committed we didn't have the correct result
This just sends them all in their own mutation - which is the same amount of queries as the bulk result so should be equivalent in performance.
=> bug: fix bulk create invites for resend

Taskfile.yaml
Linting the entire project can take ~7-10 minutes locally. 
But with this change, if you run `task go:lint CHANGED=true` it will use git to find only the changed files and lint those alone and can reduce this to single digit seconds
=> allow to run linting locally on files that have changed only

cmd/cli/cmd/organization/root.go, internal/ent/generated/gql_collection.go, internal/ent/generated/gql_edge.go, internal/ent/schema/organization.go, internal/graphapi/clientschema/schema.graphql, internal/graphapi/generated/root_.generated.go, internal/graphapi/organization_test.go, internal/graphapi/orgmembers_test.go, internal/graphapi/query/organization.graphql, internal/graphapi/query/user.graphql, internal/graphapi/schema/ent.graphql, pkg/openlaneclient/graphclient.go, pkg/openlaneclient/models.go
Adds pagination to the `organization.members` edge, it will now require `edges.node` in the request:
```
query GetOrganizationByID($organizationId: ID!) {
organization(id: $organizationId) {
id
name
members {
edges {
node {
id
role
user {
id
firstName
lastName
}
}
}
}
}
}
```
=> feat: paginate organization members

Taskfile.yaml
Now `task go:lint CHANGED=true` will run linting against all files that have changed against the main branch regardless of if they are committed or not
=> Make go:lint task much smarter

internal/graphapi/models_test.go
I was not able to test this. I ran the function a thousand times and didn't get 
any special character but this fixes it should in case it comes up and causes another test failure
=> Fix flakey tests by making sure org name matches spec

internal/httpserve/authmanager/authmanager.go, internal/httpserve/handlers/login_test.go
- Returns the active status and allows the function to continue to update the org instead of returning an error
- Adds a test to the login handler to ensure this path is covered
=> bug: fixes issue where default org was not updated when subscription expired

internal/httpserve/route/router.go, internal/httpserve/route/static.go, internal/httpserve/route/webauthn, internal/httpserve/route/wellknown.go
adds /.well-known/webauthn route so that we can realize our passkey destiny!
```
➜  ~ curl http://localhost:17608/.well-known/webauthn   
{
"origins": [
"https://www.theopenlane.io",
"https://theopenlane.io",
"https://console.theopenlane.io",
"https://api.theopenlane.io"
]
}
```
=> add /.well-known/webauthn route

internal/ent/hooks/metrics.go, internal/ent/interceptors/orgsubscription.go, internal/httpserve/authmanager/authmanager.go, internal/httpserve/handlers/tools_test.go, internal/httpserve/handlers/webhook.go, internal/httpserve/handlers/webhook_test.go
- changes the current webhook handler behavior from returning a code in the error range (4xx 5xx) when an event type we dont support is received to a success response code - we are discarding the event regardless, but when you return 4xx/5xx to stripe they attempt to resend every event up to 5+ times which is a lot of extra overhead on us (and results in getting emails from them, etc.)
- updates / corrects several of the field evaluations in the `syncOrgSubscriptionWithStripe` function to perform updates if the fields are _not_ alike rather than if they are (`if !slices.Equal` vs. `if slices.Equal` 🤦 )
- fixes a bug in `InterceptorSubscriptionURL` causing none of the URL's to be populated and populates different log error text to make it more obvious which individual URL may have been the …
=> stripe webhook updates; additional ent and webhook metrics

.pre-commit-config.yaml, internal/graphapi/clientschema/schema.graphql, internal/graphapi/generated/root_.generated.go, internal/graphapi/schema/orgmembership.graphql, pkg/openlaneclient/models.go
Allows members to be filtered on user details:
```
query OrgMemberships($where: OrgMembershipWhereInput) {
orgMemberships(where: $where) {
edges {
node {
id
role
user {
firstName
lastName
displayName
}
}
}
}
}
```
```
{
"where": {
"hasUserWith": {
"or": [
{ "displayNameContainsFold": "Matt" },
{ "firstNameContainsFold": "Matt" },
{ "lastNameContainsFold": "Matt" }
]
}
}
}
```
Result:
```
{
"data": {
"orgMemberships": {
"edges": [
{
"node": {
"id": "01JS7BNNSEAB8KE7AFMZHQRCWZ",
"role": "OWNER",
"user": {
"firstName": "matt",
"lastName": "anderson",
"displayName": "matt anderson"
}
}
}
]
}
},
"extensions": {
"auth": {
"authentication_type": "api_token",
"authorized_organization": [
"01JS7BNNRHSXY1B4ZB016EH563"
]
},
"server_latency": "56.789291ms",
"trace_id": …
```
=> feat: add user filter to org memberships

db/migrations-goose-postgres/20250421141007_aauid_not_unique_per_machine.sql, db/migrations-goose-postgres/atlas.sum, db/migrations/20250421141003_aauid_not_unique_per_machine.sql, db/migrations/atlas.sum, internal/ent/generated/migrate/schema.go, internal/ent/schema/webauthn.go
I have made the `AAGUID` not unique as this value will always be the same across all passkey devices. 
E.g All Yubi key 5C can only have one AAGUID, Yubi Key 5NFC have a different one. 
So this issue will still occur if user a from another machine tried to use 1password and another user b from another machine
used 1password already .
TLDR: `credential_id` will always change on new passkey so it is meant to be unique still but AAGUID is default across all ___passkey generating device___ for a specific manufacturer 
> I haven't added tests here as it is been notoriously hard to set up without a frontend. Mocking it can lead to scope increment of this PR but I can always do that in another PR
References
https://support.yubico.com/hc/en-us/articles/360016648959-YubiKey-hardware-FIDO2-AAGUIDs …
=> Bug: allow for same passkey to be used for multiple accounts

fga/Taskfile.yaml
Causes an infinite hang until the dev env is brought up, this shouldn't be the case as simple tasks like linting now require a full development env
=> bug: do not evaluate STORE_ID by default

go.mod, go.sum, internal/httpserve/handlers/acccountaccess.go, internal/httpserve/handlers/acccountroles.go, internal/httpserve/handlers/acccountrolesorganization.go, internal/httpserve/handlers/accountaccess_test.go, internal/httpserve/handlers/accountfeatures.go, internal/httpserve/handlers/accountfeatures_test.go, internal/httpserve/handlers/accountroles_test.go, internal/httpserve/handlers/accountrolesorganization_test.go, internal/httpserve/handlers/seed_test.go, internal/httpserve/route/accountfeatures.go, internal/httpserve/route/router.go, pkg/models/models.go
- **BREAKING**: fixes the request json to be `object_type`, `object_id`, etc. instead of `objectType`, `objectId` on the account roles REST endpoints
- Removes `DefaultAllRelations` and instead passes now relations, and allows the iam library to grab all relations for the current model under the specific object type
- Adds a `account/features` handler that will pull the account features from orgsubscriptions; this will eventually be updated to use fga instead
Example:
```
curl -s -H "Authorization: Bearer tolp_REDACTED" http://localhost:17608/v1/account/roles/organization  -H "Content-Type: application/json" |jq
{
"success": true,
"roles": [
"member",
"can_create_procedure",
"access",
"can_create_control_implementation",
"can_create_risk",
"can_invite_members",
"can_invite_admins", …
```
=> feat: updates for account roles endpoints, adds account features

internal/graphapi/clientschema/schema.graphql, internal/graphapi/control_clone.go, internal/graphapi/generated/programextended.generated.go, internal/graphapi/generated/root_.generated.go, internal/graphapi/model/gen_models.go, internal/graphapi/programextended.resolvers.go, internal/graphapi/programextended_test.go, internal/graphapi/schema/programextended.graphql, pkg/openlaneclient/models.go
Wanted to simplify the UI. While we added this to `CreateFullProgram` in #714 , the frontend 
uses `CreateProgramWithMembers`. I do not want to complicate on the frontend to have way too many 
switches bacause of a `standardID`.
I have also made `standardID` be more graphql like by making it optional from the schema level
=> Feat : add standard cloning to other program endpoints

cmd/cli/cmd/orgsubscription/root.go, docker/all-in-one/Dockerfile.all-in-one, docker/docker-compose-redis.yml, internal/ent/hooks/event.go
We had updated previously to use the `trialExpiresAt` field when `trialing`, but on the original creation we were setting `expiresAt` instead. This caused some confusion with what the UI should render.
Now it should have:
`trialExpiresAt` when `trialing` and `expiresAt` only is used after a subscription is moved out of a trial
Also updated the cli to return `trialExpiresAt` if `expiresAt` is not set
Before change the first three records, second three after:
```
expires_at       |    trial_expires_at    |             id             | stripe_subscription_status | active 
------------------------+------------------------+----------------------------+----------------------------+--------
2025-06-20 19:04:06+00 |                        | 01JVT3PFC7TAD5R02KEW2X8DZZ | trialing …
```
=> fix: set trialExpiresAt for `trialing` status

go.mod, internal/ent/hooks/group.go, internal/graphapi/group_test.go, internal/graphapi/query/group.graphql, pkg/openlaneclient/graphclient.go
You could previously add a group to an object (e.g. on a program, set a group to have edit permissions) but you couldn't do the opposite - edit a managed group to add a permission to a program. This fixes it to allow it from either object. 
I added tests as well as tested this from the UI
=> bug: fix ability to update permissions on managed group to other objects

fga/model/model.fga, fga/tests/tests.yaml, internal/graphapi/internalpolicy_test.go, internal/httpserve/handlers/acmesolver_test.go
- fixes a bug where org owners could delete a policy or procedure but not edit
by default, policies and procedures are viewable to everyone in an organization but not editable. The exception should be made for the org owner to edit and delete these objects. 
- fixes bad merge causing undefined enums in tests
=> bug: org owners should have edit access to policies and procedures

internal/ent/hooks/objectownedtuples.go, internal/graphapi/internalpolicy_test.go, internal/graphapi/models_test.go
fixes bug and adds test to verify both directions on internal policies. Same logic used across other objects.
=> bug: permissions not updated on `removed` edges from groups

internal/ent/hooks/errors.go, internal/ent/hooks/evidence.go, internal/graphapi/evidence_test.go, internal/graphapi/models_test.go
- made sure the `creation_date` cannot be in the future
- validate if present only for updates but hard requirement on new creations
- updated tests
=> Evidence: creation date cannot be in the future

cmd/cli/cmd/client.go, pkg/openlaneclient/client.go, pkg/openlaneclient/config.go, pkg/openlaneclient/csrf.go, pkg/openlaneclient/interceptor.go, pkg/openlaneclient/options.go, pkg/openlaneclient/restclient.go
Confirmed everything works with the following CSRF config:
```
csrfProtection:
enabled: true
header: X-CSRF-Token
cookie: csrf_token
secure: false 
sameSite: Lax
```
```
(⎈ |default:default)➜  core git:(bug-fix-csrf-off) task cli:user:all:another
task: [cli:user:verify] curl http://localhost:17608/v1/verify?token=x66nUl1JxpQ-CXWGPChpRV6KjwBYveQLUWkagcFQirs
{"success":true,"user_id":"01JXBWB2TWT1TV3V9XRD3SZFWC","email":"funk1@example.com","message":"success","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjAyR0dCUzY4QU0xMjE3OE0wUkVXM0NFQUdHIiwidHlwIjoiSldUIn0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjE3NjA4Iiwic3ViIjoiMDFKWEJXQjJUV1QxVFYzVjlYUkQzU1pGV0MiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDoxNzYwOCJdLCJleHAiOjE3NDk1Mjc4NTMsIm5iZiI6MTc0OTUyNDI1MywiaWF0IjoxNzQ5NTI0MjUzLCJqdGkiOiIwMWp4YndiMzE2bnRnYXA3YWJydm …
```
=> bug: keep cookies, send header via gqlgen interceptor

internal/graphapi/clientschema/schema.graphql, internal/graphapi/control_test.go, internal/graphapi/controlextended.resolvers.go, internal/graphapi/generated/controlextended.generated.go, internal/graphapi/generated/root_.generated.go, internal/graphapi/model/gen_models.go, internal/graphapi/schema/controlextended.graphql, pkg/openlaneclient/models.go
allows for the cloning of controls via a standard ID, which will take precedence over the controlIDs. This was already using in the `createFullProgram` resolver, but wasn't an input option on the `cloneControls` resolver.
=> feat: clone controls via standard ID

internal/graphapi/metrics.go, pkg/testutils/client.go
- adds metrics middleware to tests to catch errors
- removes `AroundOperations`, we can just use `AroundResponses` and use the already tracked start time
Not sure if this is correct, but when debugging I noticed `.Operation` was just `mutation` whereas `.Name` was the actual `CreateOrganization` etc. 
```
- opName = string(opCtx.Operation.Operation)
+ opName = opCtx.Operation.Name
```
=> fix: fix nil pointer panic

internal/graphapi/groupmembership.resolvers.go, internal/graphapi/orgmembers_test.go, internal/graphapi/orgmembership.resolvers.go, internal/graphapi/programmembership.resolvers.go
adds the following to the `*_membership` resolvers, so ensure tuples are deleted _before_ a hard delete, otherwise the tuples are not properly deleted. 
```
ctx = contextx.With(ctx, entfga.DeleteTuplesFirstKey{})
```
This needs to happen before any regular hooks, because the authz is a runtime hook and happens first
=> fix: hard delete needs to delete tuples first

internal/httpserve/authmanager/authmanager.go, internal/httpserve/handlers/verify_test.go
ensures we use the `defaultOrg` in the verification path
=> ensure orgID is set in JWT for verify path

go.mod, go.sum, internal/httpserve/handlers/tfavalidate_test.go
Title says it all - updates the `decrypt` method inside of the test for the handler so that it uses the updated AES-GCM encryption to perform the `decrypt` operation. v.0.13.0 of the IAM library includes updated encryption methods but the handler itself does not need to change given its calling an already wrapped method of `OTPManager.Manager.ValidateTOTP`
=> fix decrypt in totpvalidate test to use AES-GCM like the updated library does

cmd/cli/Taskfile.yaml, internal/ent/hooks/event.go
Need to use parseFS correctly when falling back to the `embed` file system
=> bug-fix slack templates

internal/ent/generated/file/file.go, internal/ent/generated/runtime/runtime.go, internal/ent/hooks/file.go, internal/ent/schema/file.go, internal/graphapi/file.resolvers.go
While the logic to delete from storage exists, it exists only in the resolver so if you deleted the file from another hook
or a db operation. the s3 or external store would never get cleaned up
=> Hook to clean up files from object store on deletion

.buildkite/lib/github.sh, .buildkite/lib/helm.sh, .buildkite/slack-utils.sh, .buildkite/tests/slack-utils.bats, .typos.toml, config/helm-values.yaml, jsonschema/schema_generator.go
The original code would extract the coreConfiguration section from the source file and replace it in the target. However, if the extraction failed or returned `null`, it would still try to load it, potentially causing the entire `coreConfiguration` to be set to null. My fix adds checks to ensure:
- We only merge if there's actual content to merge
- If the source has no coreConfiguration or it's null, we skip the merge
- If creating a new values file and coreConfiguration is null, we initialize it as an empty object{}
=> Address null coreConfiguration in Helm automation

docker/docker-compose-fga.yml, fga/model/model.fga, internal/ent/generated/runtime/runtime.go, internal/ent/generated/standard/standard.go, internal/ent/hooks/standard.go, internal/ent/schema/control.go, internal/ent/schema/standard.go, internal/graphapi/control_test.go, internal/graphapi/internalpolicy_test.go, internal/graphapi/models_test.go, internal/graphapi/programextended_test.go, internal/graphapi/standard_test.go
If an admin deletes a standard, it should cascade delete all controls under it.
org owned controls linked to the standard do not get deleted, they just get unlinked from the standard
=> Cascade delete controls

.goreleaser.yaml
Trying to fix these errors: 
>     • DEPRECATED: archives.format should not be used anymore, check https://goreleaser.com/deprecations#archivesformat for more info
>     • DEPRECATED: archives.format_overrides.format should not be used anymore, check https://goreleaser.com/deprecations#archivesformat_overridesformat for more info
>     • brews is being phased out in favor of homebrew_casks, check https://goreleaser.com/deprecations#brews for more info
=> updates for version 2 goreleaser

Taskfile.yaml, internal/ent/hooks/managedgroups.go, internal/graphapi/organization_test.go
- fixes a bug that was introduced when we no longer added users to a group by default
- adds a test
- adds cli build as a dep to `task run-dev` so it will compile in parallel with the server
=> bug: add owner to managed group iss-296

internal/httpserve/handlers/webauthn.go, pkg/models/models.go
Added the actual values since protocol.ParseCredentialRequestResponseBytes(data) would always fail since we are binding to an empty struct.
`response, err := protocol.ParseCredentialRequestResponseBody(ctx.Request().Body)` won't also work here since the value of the response body has been read already
=> Fix passkey json parsing

go.mod, go.sum, internal/ent/generate/entc.go, internal/ent/generated/export/export.go, internal/ent/generated/migrate/schema.go, internal/ent/hooks/exportable_generated.go, internal/graphapi/clientschema/schema.graphql, internal/graphapi/export_test.go, internal/graphapi/generated/root_.generated.go, internal/graphapi/schema/ent.graphql, pkg/enums/exportenums/doc.go, pkg/enums/exportenums/generate.go, pkg/enums/exporttype.go
requires: https://github.com/theopenlane/entx/pull/181
fixes a bug with exporting data from the `internalPolicy` table, which was translated as `internalpolicy` which is not a valid graphql schema
=> bug: export internalPolicy schema 

internal/httpserve/route/router.go, internal/httpserve/serveropts/option.go, pkg/corejobs/export.go, pkg/windmill/client.go
- Fixes mime type error for exports (or really anything passing `Accept` header
[gqlgqen/graphql ](https://github.com/99designs/gqlgen/blob/d5384a284c196f667c3533a87c580f6a012d2476/graphql/handler/transport/headers.go#L14) already sets a `Content-Type` header; and if an `Accept` is passed in, the current state ends up with a double `Content-Type` Header.
Current state, notice the double `Content-Type` when passing `Accept`. 
```
curl  -v http://localhost:17608/query  -H "Authorization: Bearer tola_REDACTED"  -H 'Accept: application/graphql-response+json'  --data '{"query":"query __typename { __typename }"}'   -H 'Content-Type: application/json'
...
< Content-Type: application/json;charset=utf-8
< Content-Type: application/graphql-response+json\
```
This causes the following error when …
=> bug: double content type on graphql requests

internal/ent/hooks/organization.go, internal/entitlements/entmapping/mapping.go, internal/httpserve/handlers/webhook.go, internal/httpserve/handlers/webhook_helpers.go, pkg/entitlements/subscriptions.go
Previously, when a subscription was updated, since we were only looking up existing subs based on price id, and not settting the price id when the trial was created, we ended up with duplicate modules for anything in the trial (base + compliance). 
This addresses:
-  that issue
- ensures all known fields are set on creation of subscription + modules. 
- Removes feature + feature lookup keys updates from org sub table - these were from before modules and were the features included. These are all currently empty + not used
- removes the warning on multiples items on a subscription - customers will always have multiple modules (eg base + compliance)
=> bug: duplicate org modules after sub update fix, adds all fields

internal/ent/interceptors/filter.go, internal/graphapi/trustcenter_test.go, internal/httpserve/authmanager/authmanager.go, pkg/middleware/auth/auth.go
Fixup the anonymous user id format, so that the ID can be used directly in fga queries/tuples.
=> fixup anon userid format

go.mod, go.sum, internal/graphapi/trustcenternda_test.go, internal/graphapi/trustcenterndatmpl.go
Send a new auth token to the user if they have already signed the trust center NDA.
=> trust center re-auth email

internal/ent/generated/migrate/schema.go, internal/ent/generated/trustcenterwatermarkconfig/trustcenterwatermarkconfig.go, internal/ent/generated/trustcenterwatermarkconfighistory/trustcenterwatermarkconfighistory.go, internal/graphapi/clientschema/schema.graphql, internal/graphapi/generated/root_.generated.go, internal/graphapi/schema/ent.graphql, pkg/enums/font.go
totes makes sense that graphql doesn't like the spaces, but wish it would just fail lol.
=> make the font enums more graphql friendly

internal/httpserve/handlers/webhook.go, internal/httpserve/handlers/webhook_helpers.go
confirmed this data is in the stripe event data, but looks like it wasn't on the customer. We don't actually need the customer here for anything else because of other delete functions so was able to skip the extra calls to customer as well.
=> bug: get metadata as backup from stripe sub, not customer data

.buildkite/pipeline.yaml
I can't remember how this was broken before just that "it was always failing"; looks to pass now so turning it back on to see what happens
=> un-skip apollo linter

internal/ent/hooks/organization.go, internal/graphapi/models_test.go, internal/graphapi/organization_test.go, internal/graphapi/query/organization.graphql, internal/graphapi/query/organizationsetting.graphql, internal/graphapi/query/simple/organizationsetting.graphql, pkg/openlaneclient/graphclient.go
updates the `defaultOrganizationSettings` to auto set the the following fields:
- `AllowedEmailDomains` to the email domain of the user creating the organization
- `AllowMatchingDomainsAutojoin=true`
=> feat: autoset allowed domains based on email, set autojoin true

internal/httpserve/handlers/accountfeatures_test.go, internal/httpserve/handlers/invite_test.go, internal/httpserve/handlers/refresh.go, internal/httpserve/handlers/refresh_test.go, internal/httpserve/handlers/seed_test.go
- repulls modules on refresh of the JWT and returns on the new JWT
=> fix: add modules to claims on refresh

cmd/cli/Taskfile.yaml, internal/ent/interceptors/user.go, internal/httpserve/handlers/impersonation.go
fixes a `target user not found error`:
```
curl -H 'Content-Type: application/json' -H "Authorization: Bearer tolp_REDACTED" http://localhost:17608/v1/impersonation/start -X POST -d '{"target_user_id":"01K713329YR7GT7VKXAV0ES9EN", "type": "job", "reason": "test mitb impersonation", "organization_id":"01K71333QN5VYD3HRDEJPMNEHW"}'
{"success":true,"token":"REDCATED","expires_at":"2025-10-08T00:17:39.340306-06:00","session_id":"01K7141VKSTAHQJYJZ17KP5EZ0","message":"Impersonation session started successfully"}
```
Fixes `list` command too:
```
task  cli:impersonation:target:list                                                         
task: [cli:login:creds] go run -tags cli main.go login -u admin@admin.theopenlane.io
Authentication Successful!
auth tokens successfully stored in keychain …
```
=> bug: fix taskfile for correct commands on impersonation + target user get
